#pragma once

namespace mm::plugin {

/// Plugin format the instance runs as. Format-specific decisions live only in this layer (SPEC 2.4).
enum class PluginFormat { Unknown, Vst3, Au, Standalone, Clap, Lv2, Aax };

/// Host application, as far as it can be recognised.
enum class HostKind { Unknown, AbletonLive, Logic, Reaper, Bitwig };

/// What the current format/host combination supports. Conservative: everything not verified is `false`,
/// features adapt to this instead of querying formats or hosts themselves.
///
/// Values for Live and Logic are assumptions taken from SPEC 2.1 and 6.5 that the manual host verification of
/// Phase 0 has to confirm (see docs/DECISIONS.md, "Host-Fähigkeiten").
struct HostCapabilities {
    PluginFormat format = PluginFormat::Unknown;
    HostKind host = HostKind::Unknown;

    bool midiOutput = false;          ///< MIDI generated by the plugin reaches the host
    bool noteEffectSlot = false;      ///< plugin can sit in a MIDI-FX slot of the host
    bool sameProcessCoupling = false; ///< instances of this format share one process (hub and voices)
    bool dragDropOut = false;         ///< dragging files out of the plugin window into the host
    bool keyForwarding = false;       ///< host forwards keyboard input to the plugin window
};

/// Derives the capabilities. `isMidiEffect` is true for the MIDI-FX variant (AU `aumi`).
HostCapabilities deriveCapabilities(PluginFormat format, HostKind host, bool isMidiEffect);

} // namespace mm::plugin
